spring:
  profiles:
    active: local
logging:
  level:
    root: info
--- #local
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/jayeon_test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  config:
    activate:
      on-profile: local
--- #live
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/jayeon_test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  config:
    activate:
      on-profile: live